/**
 * fix-urls.ts — Apply researched correct career URLs to companies-full.json
 */

import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const URL_FIXES: Record<string, string> = {
  // === A-F (from agent 1) ===
  "A": "https://careers.agilent.com/",
  "ACGL": "https://www.archgroup.com/careers/",
  "ADM": "https://www.adm.com/en-us/culture-and-careers/join-team-adm/",
  "AEP": "https://www.aep.com/careers/",
  "AES": "https://www.aes.com/about-us/work-at-aes",
  "AIG": "https://www.aig.com/home/careers",
  "AIZ": "https://jobs.assurant.com/en/",
  "AJG": "https://jobs.ajg.com/",
  "ALB": "https://www.albemarle.com/us/en/careers",
  "ALGN": "https://jobs.aligntech.com/",
  "AME": "https://jobs.ametek.com/",
  "AMP": "https://careers.ameriprise.com/",
  "AMT": "https://careers.americantower.com/",
  "ANET": "https://www.arista.com/en/careers",
  "AOS": "https://jobs.aosmith.com/",
  "APA": "https://apacorp.com/careers/",
  "APO": "https://www.apollo.com/careers",
  "ARE": "https://www.are.com/careers.html",
  "ARES": "https://www.aresmgmt.com/about-ares-management-corporation/careers-at-ares",
  "AVB": "https://jobs.avalonbay.com/",
  "AVY": "https://www.averydennison.com/en/home/careers/overview.html",
  "AWK": "https://jobs.amwater.com/",
  "AZO": "https://careers.autozone.com/",
  "BALL": "https://www.ball.com/careers",
  "BAX": "https://jobs.baxter.com/en",
  "BBY": "https://jobs.bestbuy.com/bby",
  "BEN": "https://www.franklintempletoncareers.com/",
  "BF.B": "https://careers.brown-forman.com/",
  "BK": "https://www.bny.com/corporate/global/en/careers.html",
  "BKR": "https://careers.bakerhughes.com/",
  "BLDR": "https://careers.bldr.com/",
  "BR": "https://broadridge.wd5.myworkdayjobs.com/Careers",
  "BRK.B": "https://www.berkshirehathaway.com/jobs/jobsmain.html",
  "BRO": "https://bbinsurance.wd1.myworkdayjobs.com/Careers",
  "BXP": "https://www.bxp.com/working-here",
  "CAG": "https://careers.conagrabrands.com/us/en/",
  "CAH": "https://jobs.cardinalhealth.com/",
  "CARR": "https://jobs.carrier.com/en",
  "CAT": "https://careers.caterpillar.com/en/",
  "CBOE": "https://careers.cboe.com/us/en/",
  "CCL": "https://jobs.carnivalcorp.com/",
  "CF": "https://careers.cfindustries.com/",
  "CHD": "https://careers.churchdwight.com/",
  "CHRW": "https://www.chrobinson.com/en-us/about-us/careers/",
  "CHTR": "https://jobs.spectrum.com/",
  "CLX": "https://www.thecloroxcompany.com/careers/",
  "CME": "https://www.cmegroup.com/careers.html",
  "CMG": "https://jobs.chipotle.com/",
  "CMS": "https://careers.consumersenergy.com/",
  "CNC": "https://jobs.centene.com/us/en/",
  "CNP": "https://careers.centerpointenergy.com/",
  "COF": "https://www.capitalonecareers.com/",
  "COO": "https://www.coopercos.com/careers/",
  "COST": "https://careers.costco.com/",
  "CPB": "https://careers.thecampbellscompany.com/",
  "CPT": "https://www.camdenliving.com/career-development",
  "CRL": "https://jobs.criver.com/",
  "CSGP": "https://www.costargroup.com/careers",
  "CSX": "https://www.csx.com/index.cfm/working-at-csx/",
  "CVS": "https://jobs.cvshealth.com/us/en",
  "DAL": "https://www.delta.com/us/en/careers/overview",
  "DD": "https://careers.dupont.com/us/en",
  "DECK": "https://www.deckers.com/careers",
  "DG": "https://careers.dollargeneral.com/",
  "DGX": "https://careers.questdiagnostics.com/",
  "DHI": "https://www.drhorton.com/careers",
  "DHR": "https://jobs.danaher.com/global/en",
  "DLR": "https://careers.digitalrealty.com/",
  "DLTR": "https://careers.dollartree.com/us/en/",
  "DOC": "https://healthpeak.com/careers/",
  "DOV": "https://careers.dovercorporation.com/",
  "DPZ": "https://jobs.dominos.com/us/",
  "DRI": "https://www.darden.com/careers",
  "DTE": "https://careers.dteenergy.com/",
  "DUK": "https://www.duke-energy.com/our-company/careers",
  "EA": "https://www.ea.com/careers",
  "ECL": "https://jobs.ecolab.com/",
  "ED": "https://careers.coned.com/",
  "EFX": "https://careers.equifax.com/en/",
  "EIX": "https://www.edisoncareers.com/",
  "EL": "https://www.elcompanies.com/en/careers",
  "ELV": "https://careers.elevancehealth.com/",
  "EME": "https://emcorgroup.com/careers",
  "EQR": "https://equityapartments.greatjob.net/",
  "EQT": "https://www.eqt.com/careers",
  "ERIE": "https://jobs.erieinsurance.com/",
  "ES": "https://jobs.eversource.com/",
  "ESS": "https://www.essexapartmenthomes.com/careers",
  "ETN": "https://www.eaton.com/us/en-us/company/careers.html",
  "EW": "https://www.edwards.com/careers",
  "EXC": "https://jobs.exeloncorp.com/",
  "EXE": "https://jobs.expandenergy.com/",
  "EXPD": "https://www.expeditors.com/careers/jobs",
  "EXPE": "https://careers.expediagroup.com/",
  "EXR": "https://careers.extraspace.com/",
  "F": "https://www.careers.ford.com/en/home.html",
  "FANG": "https://www.diamondbackenergy.com/careers",
  "FAST": "https://careers.fastenal.com/",
  "FE": "https://careers.firstenergycorp.com/",
  "FIS": "https://careers.fisglobal.com/us/en",
  "FITB": "https://www.53.com/content/fifth-third/en/careers.html",
  "FIX": "https://comfortsystemsusa.com/careers/",
  "FOX": "https://www.foxcareers.com/",
  "FOXA": "https://www.foxcareers.com/",
  "FRT": "https://www.federalrealty.com/about/careers/",

  // === G-O (from agent 2) ===
  "GD": "https://www.gd.com/careers",
  "GEHC": "https://careers.gehealthcare.com/global/en",
  "GIS": "https://careers.generalmills.com",
  "GL": "https://careers.globelifeinsurance.com",
  "GM": "https://search-careers.gm.com/en",
  "GPC": "https://jobs.genpt.com",
  "GPN": "https://jobs.globalpayments.com/en",
  "GWW": "https://jobs.grainger.com",
  "HBAN": "https://huntington-careers.com",
  "HCA": "https://careers.hcahealthcare.com",
  "HIG": "https://www.thehartford.com/careers",
  "HII": "https://hii.com/careers",
  "HLT": "https://jobs.hilton.com/us/en",
  "HON": "https://careers.honeywell.com",
  "HOOD": "https://careers.robinhood.com",
  "HRL": "https://www.hormelfoods.com/careers",
  "HSIC": "https://www.henryschein.com/us-en/corporate/career/default.aspx",
  "HST": "https://www.hosthotels.com/Our-Company/Careers",
  "HSY": "https://careers.thehersheycompany.com",
  "HUBB": "https://careers.hubbell.com",
  "HWM": "https://www.howmet.com/joinus",
  "IBKR": "https://www.interactivebrokers.com/en/general/about/careers-splash.php",
  "IDXX": "https://careers.idexx.com/us/en",
  "IEX": "https://idexcorp.com/careers",
  "IFF": "https://www.iff.com/careers",
  "INCY": "https://careers.incyte.com/jobs",
  "IP": "https://jobs.internationalpaper.com",
  "IR": "https://careers.irco.com",
  "IRM": "https://ironmountain.jobs",
  "ITW": "https://careers.itw.com/us/en",
  "J": "https://careers.jacobs.com",
  "JBHT": "https://careers.jbhunt.com",
  "JBL": "https://careers.jabil.com",
  "JCI": "https://jobs.johnsoncontrols.com",
  "JKHY": "https://careers.jackhenry.com",
  "KDP": "https://careers.keurigdrpepper.com/en",
  "KEY": "https://www.key.com/about/careers.html",
  "KHC": "https://careers.kraftheinz.com",
  "KIM": "https://www.kimcorealty.com/careers",
  "KKR": "https://www.kkr.com/careers",
  "KMI": "https://www.kindermorgan.com/Careers/Job-Opportunities",
  "KR": "https://jobs.kroger.com",
  "L": "https://loews.com/careers/default.aspx",
  "LEN": "https://careers.lennar.com",
  "LII": "https://www.lennoxinternational.com/careers",
  "LIN": "https://www.lindecareers.com/en",
  "LNT": "https://www.alliantenergy.com/careers",
  "LULU": "https://careers.lululemon.com",
  "LUV": "https://careers.southwestair.com/us/en",
  "LVS": "https://www.sands.com/company/careers/us",
  "LW": "https://careers.lambweston.com",
  "LYV": "https://www.livenationentertainment.com/careers",
  "MA": "https://careers.mastercard.com/us/en",
  "MAA": "https://careers.maac.com/us/en",
  "MAR": "https://careers.marriott.com",
  "MCHP": "https://www.microchip.com/en-us/about/careers",
  "MCK": "https://careers.mckesson.com/en",
  "MCO": "https://careers.moodys.com",
  "MDLZ": "https://www.mondelezinternational.com/careers",
  "MGM": "https://mgmresorts.wd5.myworkdayjobs.com/MGMCareers",
  "MKC": "https://careers.mccormick.com",
  "MLM": "https://jobs.jobvite.com/martinmarietta",
  "MMM": "https://www.3m.com/3M/en_US/careers-us",
  "MNST": "https://www.monsterenergy.com/en-us/careers",
  "MO": "https://careers.altria.com",
  "MOH": "https://careers.molinahealthcare.com",
  "MOS": "https://mosaicco.com/Careers",
  "MPC": "https://www.marathonpetroleum.com/Jobs",
  "MRNA": "https://www.modernatx.com/en-US/careers/life-at-moderna",
  "MRSH": "https://careers.marshmclennan.com",
  "MS": "https://www.morganstanley.com/people",
  "MTB": "https://www.mtb.com/careers",
  "MTCH": "https://mtch.com/careers",
  "MTD": "https://jobs.mt.com/en",
  "NCLH": "https://www.ncl.com/about/careers",
  "NDAQ": "https://www.nasdaq.com/about/careers",
  "NDSN": "https://www.nordson.com/en/about-us/careers",
  "NEE": "https://www.nexteraenergy.com/careers.html",
  "NOC": "https://www.northropgrumman.com/careers",
  "NSC": "https://jobs.nscorp.com",
  "NTRS": "https://www.northerntrust.com/united-states/about-us/careers",
  "NVR": "https://www.nvrcareers.com",
  "NWS": "https://dowjones.wd1.myworkdayjobs.com/News_Corp_Careers",
  "NWSA": "https://dowjones.wd1.myworkdayjobs.com/News_Corp_Careers",
  "O": "https://www.realtyincome.com/careers",
  "OMC": "https://www.omnicomgroup.com/culture/talent",
  "ORLY": "https://careers.oreillyauto.com/us/en",
  "OTIS": "https://www.otis.com/en/us/careers",

  // === P-Z (from agent 3) ===
  "PANW": "https://jobs.paloaltonetworks.com/en",
  "PCG": "https://jobs.pge.com/",
  "PEG": "https://jobs.pseg.com/",
  "PFG": "https://careers.principal.com/careers-home",
  "PGR": "https://careers.progressive.com/",
  "PH": "https://www.parker.com/us/en/careers.html",
  "PKG": "https://careers.packagingcorp.com/",
  "PNW": "https://careers.aps.com/",
  "PODD": "https://www.insulet.com/working-at-insulet",
  "POOL": "https://www.poolcorp.com/careers/",
  "PPG": "https://careers.ppg.com/us/en",
  "PPL": "https://careers.pplweb.com/jobs",
  "PRU": "https://jobs.prudential.com/us-en",
  "PSA": "https://www.publicstoragejobs.com",
  "PSKY": "https://careers.paramount.com/",
  "PWR": "https://www.quantaservices.com/careers",
  "RCL": "https://careers.royalcaribbeangroup.com/",
  "REG": "https://www.regencycenters.com/regency/careers",
  "RF": "https://careers.regions.com/us/en/",
  "RJF": "https://www.raymondjames.com/careers",
  "RL": "https://careers.ralphlauren.com/",
  "RMD": "https://careers.resmed.com/",
  "ROK": "https://www.rockwellautomation.com/en-us/careers.html",
  "ROST": "https://jobs.rossstores.com/",
  "RSG": "https://jobs.republicservices.com/us/en/careers",
  "RVTY": "https://jobs.revvity.com/",
  "SBAC": "https://careers.sbasite.com/",
  "SCHW": "https://www.schwabjobs.com/",
  "SJM": "https://www.jmsmucker.com/careers",
  "SNA": "https://www.snapon.com/EN/Careers",
  "SO": "https://southerncompany.jobs/",
  "SOLV": "https://www.solventum.com/en-us/home/our-company/careers/",
  "SPG": "https://careers.simon.com/",
  "STLD": "https://www.steeldynamics.com/careersnew/",
  "STT": "https://careers.statestreet.com/",
  "STZ": "https://www.cbrands.com/pages/careers",
  "SW": "https://www.smurfitwestrock.com/careers",
  "SWK": "https://www.stanleyblackanddecker.com/careers",
  "SYF": "https://www.synchronycareers.com/",
  "TAP": "https://www.molsoncoors.com/careers",
  "TDG": "https://www.transdigm.com/community-impact/talent-development/",
  "TDY": "https://www.teledyne.com/careers",
  "TJX": "https://www.tjx.com/careers",
  "TKO": "https://wwecorp.wd5.myworkdayjobs.com/TKO",
  "TPL": "https://www.texaspacific.com/",
  "TRGP": "https://www.targaresources.com/careers/careers-overview",
  "TROW": "https://www.troweprice.com/en/us/careers",
  "TRV": "https://careers.travelers.com/",
  "TSCO": "https://www.tractorsupply.careers/",
  "TSLA": "https://www.tesla.com/careers",
  "TSN": "https://www.tysonfoods.com/careers",
  "TTD": "https://careers.thetradedesk.com/",
  "TTWO": "https://careers.take2games.com/",
  "UAL": "https://careers.united.com/us/en",
  "UHS": "https://jobs.uhsinc.com/careers/",
  "ULTA": "https://careers.ulta.com/careers",
  "URI": "https://jobs.unitedrentals.com/",
  "V": "https://corporate.visa.com/en/careers.html",
  "VICI": "https://viciproperties.com/careers/",
  "VLTO": "https://jobs.veralto.com/global/en",
  "VMC": "https://www.vulcanmaterials.com/careers",
  "VRSK": "https://www.verisk.com/company/careers/",
  "VRTX": "https://www.vrtx.com/careers/",
  "WAT": "https://www.waters.com/nextgen/us/en/about-waters/careers.html",
  "WBD": "https://careers.wbd.com/",
  "WEC": "https://www.wecenergygroup.com/careers/",
  "WMB": "https://www.williams.com/careers/",
  "WRB": "https://careers-berkley.icims.com/jobs/intro",
  "WSM": "https://www.williams-sonomainc.com/careers/jobs/",
  "WST": "https://careers.westpharma.com/",
  "WTW": "https://careers.wtwco.com/",
  "WYNN": "https://www.wynnresorts.com/careers",
  "YUM": "https://www.yum.com/careers/",
  "ZBH": "https://careers.zimmerbiomet.com/us/en/",
  "XYZ": "https://block.xyz/careers/jobs",

  // === Additional known-good overrides for original IT companies that had crawl errors ===
  "JNPR": "https://www.juniper.net/us/en/company/careers.html",
};

async function main() {
  const companiesPath = join(ROOT, "data", "companies-full.json");
  const companies = JSON.parse(await readFile(companiesPath, "utf8"));

  let fixed = 0;
  for (const c of companies) {
    const newUrl = URL_FIXES[c.ticker];
    if (newUrl && newUrl !== c.careers_url) {
      console.log(`  ${c.ticker.padEnd(6)} ${c.careers_url.slice(0, 50).padEnd(52)} → ${newUrl.slice(0, 50)}`);
      c.careers_url = newUrl;
      fixed++;
    }
  }

  await writeFile(companiesPath, JSON.stringify(companies, null, 2));
  console.log(`\n✅ Fixed ${fixed} career URLs in companies-full.json`);
}

main().catch(console.error);
